linters:
  enable:
    - bodyclose
    - deadcode
    - dogsled
    - gocyclo
    - goimports
    - revive
    - gosec
    - gosimple
    - govet
    - ineffassign
    - lll
    - megacheck
    - misspell
    - nakedret
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - errorlint
    - bodyclose
    - gci
    - forbidigo

run:
  timeout: 5m

# all available settings of specific linters
linters-settings:
  gosec:
    config:
      G306: "0644"
  lll:
    line-length: 150

  forbidigo:
    forbid:
      - '^errors\.Wrap$'
      - '^errors\.Wrapf$'
      - '^fmt\.Errorf$'
      - '^errors\.Errorf$'

  gci:
    local-prefixes: github.com/RasaHQ/rasactl
