changelog:
  # Set it to true if you wish to skip the changelog generation.
  # This may result in an empty release notes on GitHub/GitLab/Gitea.
  skip: true

  # Sorts the changelog by the commit's messages.
  # Could either be asc, desc or empty
  # Default is empty
  sort: asc

  filters:

    # Commit messages matching the regexp listed here will be removed from
    # the changelog
    # Default is empty
    exclude:
      - '^docs:'
      - typo
      - (?i)foo


builds:
  - id: darwin
    binary: rasactl
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/macos/amd64
      - PKG_CONFIG_PATH=/sysroot/macos/amd64/usr/local/lib/pkgconfig
      - CC=o64-clang
      - CXX=o64-clang++
    flags:
      - -mod=readonly
    ldflags:
       - -s -w -X "github.com/RasaHQ/rasactl/pkg/version.VERSION={{.Env.VERSION}}"
  - id: linux
    binary: rasactl
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_FLAGS=--sysroot=/sysroot/linux/amd64
      - CGO_LDFLAGS=--sysroot=/sysroot/linux/amd64
      - PKG_CONFIG_SYSROOT_DIR=/sysroot/linux/amd64
      - PKG_CONFIG_PATH=/sysroot/linux/amd64/usr/lib/x86_64-linux-gnu/pkgconfig
    flags:
      - -mod=readonly
    ldflags:
      - -s -w -X "github.com/RasaHQ/rasactl/pkg/version.VERSION={{.Env.VERSION}}"

archives:
  - id: rasactl
    builds:
      - darwin
      - linux
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    wrap_in_directory: true

#  - id: darwin
#    env:
#      - CGO_ENABLED=1
#      - CGO_CFLAGS=-mmacosx-version-min=10.11
#    goos:
#      - darwin
#    ldflags:
#    - -s -w -X "github.com/RasaHQ/rasactl/pkg/version.VERSION={{.Env.VERSION}}"
#
#  - id: linux
#    env:
#      - CGO_ENABLED=1
#    goarch:
#      - amd64
#    goos:
#      - linux
#    ldflags:
#    - -s -w -X "github.com/RasaHQ/rasactl/pkg/version.VERSION={{.Env.VERSION}}"

brews:
  - name: rasactl
    tap:
      owner: RasaHQ
      name: homebrew-rasactl
      token: "{{ .Env.RASABOT_GITHUB_TOKEN }}"

    test: |
      system "#{bin}/rasactl --version"

    # Git author used to commit to the repository.
    # Defaults are shown.
    commit_author:
      name: rasabot
      email: rasabot@rasa.com

    folder: Formula

    homepage: "https://github.com/RasaHQ/rasactl"

    # Template of your app's description.
    # Default is empty.
    description: "rasactl deploys Rasa X / Enterprise on your local or remote Kubernetes cluster and manages Rasa X / Enterprise deployments."
