changelog:
  # Set it to true if you wish to skip the changelog generation.
  # This may result in an empty release notes on GitHub/GitLab/Gitea.
  skip: true

  # Sorts the changelog by the commit's messages.
  # Could either be asc, desc or empty
  # Default is empty
  sort: asc

  filters:

    # Commit messages matching the regexp listed here will be removed from
    # the changelog
    # Default is empty
    exclude:
      - '^docs:'
      - typo
      - (?i)foo

builds:
  - id: darwin
    env:
      - CGO_ENABLED=1
      - CGO_CFLAGS=-mmacosx-version-min=10.11
    goos:
      - darwin
    ldflags:
    - -s -w -X "github.com/RasaHQ/rasactl/pkg/version.VERSION={{.Env.VERSION}}"

  - id: linux
    env:
      - CGO_ENABLED=1
    goarch:
      - amd64
    goos:
      - linux
    ldflags:
    - -s -w -X "github.com/RasaHQ/rasactl/pkg/version.VERSION={{.Env.VERSION}}"
