---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-default
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 2Gi
  hostPath:
    path: /rasa_projects/default
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-default
spec:
  volumeName: pv-default
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
