name: Continuous Integration

on:
  push:
    branches:
    - 'main'
    tags:
    - '**'
  pull_request:
    types: [opened, synchronize, labeled]


jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

  build:
    runs-on: ubuntu-latest
    needs: [golangci]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build
        run: |
          docker run \
            --rm \
            -e CGO_ENABLED=1 -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -e VERSION=${{ env.VERSION }} \
            -e RASABOT_GITHUB_TOKEN=${{ secrets.RASABOT_GITHUB_TOKEN }} \
            -v `pwd`:/go/src/rasactl \
            -w /go/src/rasactl \
            ghcr.io/tczekajlo/golang-cross:v1.17.0 \
            build --snapshot
