name: Publish Docker image - CoreDNS

on:
  release:
    types: [published]
  pull_request:
    types: [opened, synchronize, labeled]

jobs:
  push_to_registry:
    name: Push Docker image to the Container registry
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

#      - name: Log in to the Container registry
#        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
#        with:
#          registry: ghcr.io
#          username: ${{ github.actor }}
#          password: ${{ secrets.GITHUB_TOKEN }}

#      - name: Build and push Docker images
#        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
#        with:
#          context: misc/coredns
#          push: true
#          # it's very simple configuration that's why the tag is hardcoded
#          tags: "ghcr.io/rasahq/rasactl:coredns-1.8.5"
