name: Release

on:
  push:
    tags:
      - '*'

env:
  GO_VERSION: 1.17.6

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2

  build:
    runs-on: ubuntu-latest
    needs: [golangci]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get the version
        id: get_version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Generate changelog
        run: |
          brew tap git-chglog/git-chglog
          brew install git-chglog

          git-chglog --output /home/runner/release_changelog.md --template .chglog/RELEASE_CHANGELOG.tpl.md ${VERSION}
          cat /home/runner/release_changelog.md

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v3
        with:
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}

      - name: Build
        run: |
          docker run \
            --rm \
            -e CGO_ENABLED=1 -e GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} -e VERSION=${{ env.VERSION }} \
            -e RASABOT_GITHUB_TOKEN=${{ secrets.RASABOT_GITHUB_TOKEN }} \
            -e GPG_FINGERPRINT=${{ steps.import_gpg.outputs.fingerprint }} \
            -v `pwd`:/go/src/rasactl \
            -v /home/runner/release_changelog.md:/home/runner/release_changelog.md \
            -v /home/runner/.gnupg:/root/.gnupg \
            -w /go/src/rasactl \
            ghcr.io/tczekajlo/golang-cross:v${{ env.GO_VERSION }} release --release-notes=/home/runner/release_changelog.md
